# Generated by Django 5.2.7 on 2025-10-03 15:20

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_conta', models.CharField(default=users.models.gerar_numero_conta, max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('data_de_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX)XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')])),
                ('admUser', models.BooleanField(default=False)),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo_de_conta', models.CharField(max_length=20)),
                ('status_conta', models.CharField(default='ativa', max_length=20)),
            ],
        ),
    ]
