# Generated by Django 5.2.7 on 2025-10-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_solicitacaocredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creditos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
