# Generated by Django 5.2.7 on 2025-10-23 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluída'), ('falhou', 'Falhou')], default='concluida', max_length=10),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
