# Generated by Django 5.2.7 on 2025-10-29 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transferencia_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito')], max_length=10)),
                ('limite_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cor_hex', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='CartaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='pendente', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('resposta_gerente', models.TextField(blank=True, null=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='users.cartao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_solicitados', to='users.cliente')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_gerenciados', to='users.gerente')),
            ],
        ),
    ]
