# Generated by Django 5.2.7 on 2025-10-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cartao_cartaocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocliente',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cartaocliente',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartaocliente',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cartaocliente',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
